Activacion: "Test"
#NO BORRAR ESTO O MODIFICAR EL FILE, PUEDE OCASIONAR ERRORES
ConsumidodoFungalClumps:
  - ""
#nose como funcionara eso pero bueno tendria que salir asi
#ConsumidoFungalClumps:
#- UUID del Jugador
#Si hay un jugador que tiene problemas con el item pueden buscar la UUID por NameMC https://es.namemc.com y se saca la del jugador que tiene problemas